# Alarm configuration variables
target_capacity_actions_enabled = "true"
target_capacity_namespace = "AWS/EC2Spot"
target_capacity_metric = "MaxPercentCapacityAllocation"
target_capacity_statistic = "Average"
target_capacity_period = "300"
target_capacity_evaluation_period = "2"
target_capacity_high_threshold = "0"
target_capacity_low_threshold = "100"
target_capacity_unit = "Percent"
target_capacity_alarm_type = "AWS::CloudWatch::Alarm"
target_capacity_alarmactions = ":SPOT-PROD"

scale_actions_enabled = "true"
scale_namespace = "AWS/SQS"
scale_metric = "ApproximateNumberOfMessagesVisible"
scale_statistic = "Average"
scale_period = "300"
scale_evaluation_period = "2"
scale_up_threshold  = "10000"
scale_down_threshold  = "100"
scale_unit = "Percent"
scale_alarm_type = "AWS::CloudWatch::Alarm"
scale_alarm_dimensions_value = "AggregationReadyUsers-prod-na"
sns_topic = "SPOT-PROD"
